"""Design tokens for the EASY DEPLOY visual system."""

from copy import deepcopy


DEFAULT_SKIN = "neutral_tech"

SKIN_ORDER = (
    "neutral_tech",
    "blue_steel",
    "olive_ops",
    "graphite",
    "classic",
    "high_contrast",
)

BUTTON_STYLES = (
    "primary",
    "secondary",
    "danger",
    "warning",
    "ghost",
    "success",
    "info",
)

DESIGN_TOKENS = {
    "spacing": {
        "base": 8,
        "xs": 4,
        "sm": 8,
        "md": 16,
        "lg": 24,
        "xl": 32,
    },
    "radius": {
        "button": 8,
        "card": 8,
        "modal": 12,
        "badge": 8,
        "input": 8,
    },
    "font": {
        "family": "Segoe UI",
        "mono": "Consolas",
        "title": ("Segoe UI", 28, "bold"),
        "section": ("Segoe UI", 20, "bold"),
        "body": ("Segoe UI", 13),
        "label": ("Segoe UI", 12, "bold"),
        "caption": ("Segoe UI", 11),
        "mono_body": ("Consolas", 12),
    },
    "button_styles": BUTTON_STYLES,
}

SKINS = {
    "neutral_tech": {
        "name": "Neutral Tech",
        "dark": {
            "canvas": "#111113",
            "panel": "#1B1B1F",
            "card": "#242428",
            "card_hover": "#2A2A2F",
            "border": "#35353A",
            "border_soft": "#2D2D32",
            "border_focus": "#2D8F83",
            "text_primary": "#F5F5F7",
            "text_secondary": "#D4D4D8",
            "text_muted": "#A1A1AA",
            "text_disabled": "#71717A",
        },
        "light": {
            "canvas": "#F4F1EA",
            "panel": "#F9F7F1",
            "card": "#FCFAF5",
            "card_hover": "#EFECE4",
            "border": "#DCD6CB",
            "border_soft": "#E8E2D7",
            "border_focus": "#2D8F83",
            "text_primary": "#1F2933",
            "text_secondary": "#5F6670",
            "text_muted": "#71717A",
            "text_disabled": "#A1A1AA",
        },
        "state": {
            "accent": "#2D8F83",
            "accent_hover": "#27796F",
            "success": "#2F855A",
            "warning": "#B7791F",
            "danger": "#B64A3B",
            "info": "#3B6EA8",
            "secondary": "#5B6472",
            "secondary_hover": "#47515F",
        },
    },
    "blue_steel": {
        "name": "Blue Steel",
        "dark": {
            "canvas": "#101216",
            "panel": "#1A1D23",
            "card": "#232832",
            "card_hover": "#2A303B",
            "border": "#363D49",
            "border_soft": "#2C333D",
            "border_focus": "#4C7EA8",
            "text_primary": "#F4F7FA",
            "text_secondary": "#D5DCE5",
            "text_muted": "#9AA6B2",
            "text_disabled": "#6F7A86",
        },
        "light": {
            "canvas": "#EEF3F7",
            "panel": "#F5F8FA",
            "card": "#FBFCFD",
            "card_hover": "#E7F0F6",
            "border": "#CBD8E4",
            "border_soft": "#DDE7EF",
            "border_focus": "#4C7EA8",
            "text_primary": "#17202A",
            "text_secondary": "#3F4D5C",
            "text_muted": "#728092",
            "text_disabled": "#A3ACB8",
        },
        "state": {
            "accent": "#4C7EA8",
            "accent_hover": "#3E6A8F",
            "success": "#2F855A",
            "warning": "#B7791F",
            "danger": "#B64A3B",
            "info": "#3B6EA8",
            "secondary": "#5B6472",
            "secondary_hover": "#47515F",
        },
    },
    "olive_ops": {
        "name": "Olive Ops",
        "dark": {
            "canvas": "#11130F",
            "panel": "#1B1E18",
            "card": "#242820",
            "card_hover": "#2B3027",
            "border": "#384032",
            "border_soft": "#30372C",
            "border_focus": "#758B45",
            "text_primary": "#F5F7F0",
            "text_secondary": "#D9DEC9",
            "text_muted": "#A7AF92",
            "text_disabled": "#747D63",
        },
        "light": {
            "canvas": "#F4F5EF",
            "panel": "#FAFAF5",
            "card": "#FAFBF7",
            "card_hover": "#F0F3E9",
            "border": "#DDE3D1",
            "border_soft": "#E8ECE0",
            "border_focus": "#758B45",
            "text_primary": "#1D2118",
            "text_secondary": "#454C39",
            "text_muted": "#747D63",
            "text_disabled": "#A4AB97",
        },
        "state": {
            "accent": "#758B45",
            "accent_hover": "#61743A",
            "success": "#4F7A3A",
            "warning": "#A7781F",
            "danger": "#A94B3E",
            "info": "#496F8E",
            "secondary": "#626B59",
            "secondary_hover": "#4F5847",
        },
    },
    "graphite": {
        "name": "Graphite",
        "dark": {
            "canvas": "#0D0E10",
            "panel": "#17181B",
            "card": "#202126",
            "card_hover": "#282A30",
            "border": "#33363D",
            "border_soft": "#2A2D33",
            "border_focus": "#7C8A9A",
            "text_primary": "#F4F5F7",
            "text_secondary": "#D0D4DA",
            "text_muted": "#9AA1AB",
            "text_disabled": "#6F7680",
        },
        "light": {
            "canvas": "#ECEFF3",
            "panel": "#F3F5F7",
            "card": "#FAFAFB",
            "card_hover": "#E4E8ED",
            "border": "#C3CAD4",
            "border_soft": "#D5DBE3",
            "border_focus": "#667085",
            "text_primary": "#1D232B",
            "text_secondary": "#4F5966",
            "text_muted": "#6F7884",
            "text_disabled": "#9CA3AF",
        },
        "state": {
            "accent": "#667085",
            "accent_hover": "#525A6A",
            "success": "#2F855A",
            "warning": "#A66B18",
            "danger": "#A94B3E",
            "info": "#496F8E",
            "secondary": "#5B6472",
            "secondary_hover": "#47515F",
        },
    },
    "high_contrast": {
        "name": "High Contrast",
        "dark": {
            "canvas": "#050506",
            "panel": "#111114",
            "card": "#1C1C20",
            "card_hover": "#28282E",
            "border": "#5F636B",
            "border_soft": "#42464E",
            "border_focus": "#31B69F",
            "text_primary": "#FFFFFF",
            "text_secondary": "#E4E7EC",
            "text_muted": "#C5CAD3",
            "text_disabled": "#89909B",
        },
        "light": {
            "canvas": "#F2F4F6",
            "panel": "#F7F8FA",
            "card": "#FFFFFF",
            "card_hover": "#E6EDF3",
            "border": "#8A93A3",
            "border_soft": "#C9CED8",
            "border_focus": "#167C70",
            "text_primary": "#09090B",
            "text_secondary": "#27272A",
            "text_muted": "#52525B",
            "text_disabled": "#71717A",
        },
        "state": {
            "accent": "#167C70",
            "accent_hover": "#0F665C",
            "success": "#176B3A",
            "warning": "#8A5A00",
            "danger": "#9F2D20",
            "info": "#245E9B",
            "secondary": "#3F4652",
            "secondary_hover": "#2F3540",
        },
    },
    "classic": {
        "name": "Classic",
        "dark": {
            "canvas": "#101012",
            "panel": "#1F1F22",
            "card": "#26262A",
            "card_hover": "#2B3031",
            "border": "#3A3A40",
            "border_soft": "#303034",
            "border_focus": "#2F9E8F",
            "text_primary": "#F9FAFB",
            "text_secondary": "#E5E7EB",
            "text_muted": "#A1A1AA",
            "text_disabled": "#71717A",
        },
        "light": {
            "canvas": "#F5F7FA",
            "panel": "#F9FAFB",
            "card": "#FFFFFF",
            "card_hover": "#EEF6F4",
            "border": "#D7DAE0",
            "border_soft": "#E5E7EB",
            "border_focus": "#2F9E8F",
            "text_primary": "#18181B",
            "text_secondary": "#3F3F46",
            "text_muted": "#71717A",
            "text_disabled": "#A1A1AA",
        },
        "state": {
            "accent": "#2F9E8F",
            "accent_hover": "#258176",
            "success": "#16803C",
            "warning": "#D97706",
            "danger": "#B42318",
            "info": "#2563EB",
            "secondary": "#6B7280",
            "secondary_hover": "#4B5563",
        },
    },
}


def get_skin_tokens(name):
    """Return a defensive copy of a skin token set."""
    skin_name = name if name in SKINS else DEFAULT_SKIN
    return deepcopy(SKINS[skin_name])
