export const terminalScripts: Record<string, string[]> = {
  // Active Directory Domain Controller simulations
  ad_dc1: [
    '⚡ C:\\> powershell.exe -NoProfile -ExecutionPolicy Bypass',
    'Windows PowerShell (C) Microsoft Corporation. Todos los derechos reservados.',
    '',
    'PS C:\\Users\\Administrador> Install-WindowsFeature AD-Domain-Services -IncludeManagementTools',
    'Success Restart Needed Exit Code Feature Result',
    '------- -------------- --------- --------------',
    'True    No             Success   {Servicios de dominio de Active Directory...}',
    '',
    'PS C:\\Users\\Administrador> Import-Module ADDSDeployment',
    'PS C:\\Users\\Administrador> Install-ADDSForest -DomainName "easydeploy.local" -ForestMode WinThreshold -DomainMode WinThreshold -Force:$true -SafeModeAdministratorPassword (ConvertTo-SecureString "Pass1234!" -AsPlainText -Force)',
    '[✓] Validación local: Comprobando requisitos de red y registro SRV...',
    '[✓] Validación local: Comprobando sufijos DNS configurados...',
    '[+] Iniciando servicio de directorio en EasyDeploy-DC1 (easydeploy.local)',
    '[!] El adaptador de red será configurado automáticamente con DNS local (127.0.0.1)',
    '[i] Creando base de datos NTDS.dit y archivos de registro SYSVOL en C:\\Windows\\NTDS...',
    '[i] Configurando base de datos de esquema y catálogo global para el nuevo bosque...',
    '[✓] Bosque y dominio "easydeploy.local" creados correctamente.',
    '⚠️ ADVERTENCIA: Se recomienda reiniciar el equipo para completar la promoción.',
    'PROCESO FINALIZADO CON ÉXITO.'
  ],
  ad_dc2: [
    '⚡ C:\\> powershell.exe -Command "Install-ADDSDomainController -DomainName easydeploy.local -NoGlobalCatalog:$false -InstallDns:$true"',
    'Windows PowerShell - Agregando Controlador de Dominio Adicional...',
    '',
    '[i] Conectando con el controlador existente en easydeploy.local...',
    '[✓] Credenciales de Administrador de Dominio validadas con éxito.',
    '[+] Iniciando replicación de metadatos del esquema (782 objetos)...',
    '[+] Replicando partición de configuración... (Completado)',
    '[+] Replicando base de datos SYSVOL y catálogos de grupo GPO...',
    '[✓] EasyDeploy-DC2 ha sido registrado en el sitio "Default-First-Site-Name".',
    '⚠️ Reiniciando controlador de dominio adicional para aplicar cambios estructurales...'
  ],
  ad_gpo: [
    '⚡ C:\\> gpupdate /force',
    'Actualizando directivas de grupo para el equipo y el usuario...',
    '',
    '[+] Directiva de equipo se actualizó de forma correcta.',
    '[+] Directiva de usuario se actualizó de forma correcta.',
    '',
    'PS C:\\Users\\Administrador> Get-GPOReport -All -ReportType Html -Path C:\\GPO_Report.html',
    '[✓] Informe generado en C:\\GPO_Report.html. Políticas activas: 14 aplicadas, 2 omitidas.'
  ],
  ad_users: [
    '⚡ C:\\> powershell.exe -File .\\create-ad-users.ps1',
    'Cargando base de datos para importación masiva...',
    'Estructura detectada: "easydeploy.local/Usuarios/Departamentos"',
    '',
    '[+] Creando Unidad Organizativa (OU) "Seguridad" ... OK',
    '[+] Creando Unidad Organizativa (OU) "Sistemas" ... OK',
    '[+] Importando cuenta: Pedro Gómez (pgomez@easydeploy.local) - Generando contraseña...',
    '[+] Importando cuenta: Marta Torres (mtorres@easydeploy.local) - Grupo "Domain Admins"...',
    '[+] Importando cuenta: Carlos Ruiz (cruiz@easydeploy.local) - Grupo "Sistemas"...',
    '[✓] Se importaron 18 usuarios de forma exitosa en el Active Directory.'
  ],
  ad_repadmin: [
    '⚡ C:\\> repadmin /showrepl',
    'EasyDeploy-DC1.easydeploy.local',
    'DSA Options: IS_GC',
    'Site: Default-First-Site-Name',
    'Local object GUID: 8ae45a1f-b519-482d-8956-6512b93dfaa2',
    '',
    '==== ENTRANTES DE VECINOS DE REPLICACIÓN =====================================',
    'DC=easydeploy,DC=local',
    '    Default-First-Site-Name\\EasyDeploy-DC2 via RPC',
    '        Object GUID: e9a2c140-fdc2-48a0-983c-62bf087b32d1',
    '        Last attempt @ 2026-05-25 14:02:12 was successful.',
    'CN=Configuration,DC=easydeploy,DC=local',
    '    Default-First-Site-Name\\EasyDeploy-DC2 via RPC',
    '        Object GUID: e9a2c140-fdc2-48a0-983c-62bf087b32d1',
    '        Last attempt @ 2026-05-25 14:02:13 was successful.',
    '',
    '[✓] Todo el bosque se encuentra en estado saludable. 0 fallos de replicación reportados.'
  ],
  ad_d2_d4: [
    '⚡ C:\\> reg add "HKLM\\System\\CurrentControlSet\\Services\\NtFrs\\Parameters\\Backup/Restore\\Process at Startup" /v BurFlags /t REG_DWORD /d 212 /f',
    'La operación de Registro se completó correctamente.',
    '',
    'PS C:\\Users\\Administrador> Restart-Service NTFRS',
    '[!] Deteniendo servicio de Servidor de Replicación de Archivos (NtFrs)...',
    '[!] Iniciando servicio de Servidor de Replicación de Archivos (NtFrs)...',
    '[i] Levantando sysvol en modo D4 (Autoritativo / Restoring base master).',
    '[✓] SYSVOL iniciado en modo primario. Los controladores adicionales comenzarán a sincronizar de inmediato.'
  ],

  // MS Exchange Simulation
  exchange_prereqs: [
    '⚡ C:\\> powershell.exe -Command "Install-WindowsFeature NET-Framework-45-Features, Server-Media-Foundation, RPC-over-HTTP-proxy, RSAT-Clustering, RSAT-Clustering-CmdInterface, RSAT-Clustering-Mgmt, RSAT-Clustering-PowerShell, WAS-Process-Model, Web-Asp-Net45, Web-Basic-Auth, Web-Digest-Auth, Web-Dir-Browsing, Web-Http-Errors, Web-Http-Logging, Web-Http-Redirect, Web-Http-Tracing, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Lgcy-Mgmt-Console, Web-Metabase, Web-Mgmt-Console, Web-Mgmt-Service, Web-Net-Ext45, Web-Request-Monitor, Web-Static-Content, Web-Windows-Auth, Web-WMI, Windows-Identity-Foundation, RSAT-ADDS"',
    'Comprobando dependencias para la instalación de Microsoft Exchange Server 2019...',
    '',
    '[+] Instalando componentes del servidor IIS... OK',
    '[+] Instalando características WAS y ASP.NET 4.5... OK',
    '[+] Configurando soporte RPC sobre HTTP... OK',
    '[+] Instalando Unified Communications Managed API (UCMA) 4.0... OK',
    '[⚡] Instalando Visual C++ Redistributable 2013/2019... OK',
    '[✓] Todos los prerrequisitos del sistema operativo se completaron de manera satisfactoria. El sistema está listo para preparar Active Directory Schema.'
  ],
  exchange_prepare_ad: [
    '⚡ C:\\> setup.exe /PrepareSchema /IAcceptExchangeServerLicenseTerms_DiagnosticDataON',
    'Microsoft Exchange Server 2019 Cumulative Update Setup',
    '',
    'Cargando recursos de instalación...',
    'Iniciando proceso de extensión del Esquema de Active Directory...',
    '[+] Comprobando conexión con el Maestro de Esquema (Schema Master) EasyDeploy-DC1...',
    '[+] Escribiendo atributos del catálogo Exchange en Active Directory schema...',
    '[✓] AD Schema extendido con éxito. Versión actual: ObjectVersion: 17351',
    '',
    'PS C:\\> setup.exe /PrepareAD /OrganizationName:"EasyDeployOrg" /IAcceptExchangeServerLicenseTerms_DiagnosticDataON',
    'Iniciando preparación del Bosque de Active Directory...',
    '[+] Registrando contenedores administrativos en la partición de Configuración...',
    '[+] Creando grupos de seguridad globales: "Exchange Organization Administrators", "Exchange Recipient Administrators", "Exchange Managed Availability Servers".',
    '[✓] Active Directory preparado correctamente para hospedar Exchange.'
  ],
  exchange_install: [
    '⚡ C:\\> setup.exe /Mode:Install /Roles:Mailbox /IAcceptExchangeServerLicenseTerms_DiagnosticDataON',
    'Instalador de Microsoft Exchange Server 2019 CU15',
    '--------------------------------------------------------',
    'Iniciando copia de archivos del instalador local... (4.3 GB)',
    '',
    'Paso 1 de 14: Copiar archivos de Exchange... (100%)',
    'Paso 2 de 14: Configurar y registrar archivos de instalación... (100%)',
    'Paso 3 de 14: Análisis de requisitos previos de Exchange... (Aprobado)',
    'Paso 4 de 14: Preparar servicio de directorio... (100%)',
    'Paso 5 de 14: Install Active Directory Container... (100%)',
    'Paso 6 de 14: Servicio de Transporte del Concentrador... (100%)',
    'Paso 7 de 14: Servicio de Acceso de Clientes (CAS)... (100%)',
    'Paso 8 de 14: Servicio de Buzones (Mailbox Server)... (100%)',
    'Paso 9 de 14: Servicio de Mensajería Unificada... (100%)',
    'Paso 10 de 14: Configurar base de datos inicial de Exchange... (Mailbox Database 083103)',
    'Paso 11 de 14: Configurando conectores de envío y recepción... (100%)',
    'Paso 12 de 14: Registrando servicios de Windows... (MSExchangeMailboxAssistants, MSExchangeTransport)',
    'Paso 13 de 14: Configurando el portal de administración ECP e IIS local...',
    'Paso 14 de 14: Finalizando instalación de Exchange y cargando dependencias...',
    '',
    '[✓] Microsoft Exchange Server ha sido instalado exitosamente.',
    '⚠️ Acceda al panel web mediante: https://easydeploy-dc1.easydeploy.local/ecp/',
    'PROCESO AUTOMÁTICO DE IMPLEMENTACIÓN FINALIZADO.'
  ],
  exchange_users: [
    '⚡ C:\\> powershell.exe -Command "Import-Module ExchangePowerShell; Get-User -RecipientTypeDetails User | Enable-Mailbox -Database \'Mailbox Database 083103\'"',
    'Abriendo Shell de Administración de Exchange...',
    '',
    '[i] Vinculando base de datos activa: "Mailbox Database 083103"',
    '[+] Creando Buzón para: Pedro Gómez (OU: Seguridad) -> Buzón habilitado.',
    '[+] Creando Buzón para: Marta Torres (OU: Sistemas) -> Buzón habilitado (Cuota ilimitada).',
    '[+] Creando Buzón para: Carlos Ruiz (OU: Sistemas) -> Buzón habilitado.',
    '[✓] Buzones asignados correctamente para los 18 usuarios del dominio Active Directory.',
    'Probando flujo SMTP local: [DC1 -> Local Inbox] ... [Éxito]'
  ],
  exchange_recover: [
    '⚡ C:\\> setup.exe /Mode:RecoverServer /IAcceptExchangeServerLicenseTerms_DiagnosticDataON',
    'Iniciando Modo de Recuperación de Desastres de Exchange Server...',
    'Buscando este servidor registrado en la topología de Active Directory...',
    'Servidor EasyDeploy-EXC encontrado en AD.',
    '',
    '[i] Reconstruyendo estructura local según los metadatos de configuración en Active Directory...',
    '[+] Reinstalando binarios del rol de buzón de correo...',
    '[+] Restaurando bases de datos y registros en cache local...',
    '[✓] Servidor recuperado con éxito. Roles restaurados: Mailbox, Client Access.'
  ],

  // Skype for Business Simulation
  skype_prereqs: [
    '⚡ C:\\> powershell.exe -Command "Install-WindowsFeature NET-Framework-45-Core, Windows-Identity-Foundation, Web-Static-Content, Web-Default-Doc, Web-Http-Errors, Web-Asp-Net45, Web-Net-Ext45, Web-ISAPI-Ext, Web-ISAPI-Filter, Web-Http-Logging, Web-Windows-Auth, Web-Client-Auth, Web-Filtering, Web-Stat-Compression, Web-Dyn-Compression, Web-Mgmt-Console, Microsoft-Windows-MediaFoundation"',
    'Iniciando prerrequisitos para Skype for Business Server 2019...',
    '',
    '[+] Verificando .NET Framework 4.5.2... OK',
    '[+] Registrando IIS Dynamic / Static compression... OK',
    '[+] Comprobando servicios de Active Directory schema... [OK - Detectado easydeploy.local]',
    '[+] Generando herramientas administrativas para Skype Topology Builder...',
    '[✓] Entorno listo para la instalación de Skype.'
  ],
  skype_install: [
    '⚡ C:\\> setup.exe /mode:installsfbs /IAcceptSkypeLicenseTerms',
    'Skype for Business Server 2019 Setup Utility',
    '--------------------------------------------------------',
    '[i] Instalando base de datos SQL local Express para configuración de topología local...',
    '[✓] SQL Server Express (RTCSrv) instalado de forma local.',
    '[+] Descargando metadatos XML de la topología desde el almacén central (CMS)...',
    '[i] Solicitando certificados de comunicación interna del dominio easydeploy.local...',
    '[+] Asignando certificado de Skype en IIS Bindings (Puerto 4443)... OK',
    '[+] Iniciando servicios de Skype for Business:',
    '    - RTCSRV (Servicio de Front-End): Iniciando... [Ejecutando]',
    '    - RTCPX (Servicio de Proxy web): Iniciando... [Ejecutando]',
    '    - RTCCMP (Servicio de Conferencia): Iniciando... [Ejecutando]',
    '[✓] Skype for Business Server implementado con éxito en EasyDeploy-SFB.'
  ],
  skype_perms: [
    '⚡ C:\\> Grant-CsSetupPermission -OU "OU=Sistemas,DC=easydeploy,DC=local" -Domain easydeploy.local',
    'Asignando privilegios administrativos de Skype en Active Directory...',
    '',
    '[+] Otorgando permisos RTCUniversalAdmins en OU=Sistemas... OK',
    '[+] Otorgando permisos RTCUniversalUserAdmins en OU=Sistemas... OK',
    'PS C:\\> Enable-CsUser -Identity "mtorres@easydeploy.local" -RegistrarPool "pool1.easydeploy.local" -SipAddressType EmailAddress',
    '[✓] Usuario Marta Torres habilitado para Skype con dirección SIP: sip:mtorres@easydeploy.local',
    '[✓] Permisos y usuarios habilitados de forma exitosa.'
  ],
  skype_dns: [
    '⚡ C:\\> dnscmd 127.0.0.1 /RecordAdd easydeploy.local _sipinternaltls._tcp SRV 0 0 5061 pool1.easydeploy.local',
    'Agregando registro SRV de DNS para autodiscover interno de Skype...',
    'Comprobando resolución DNS local...',
    '',
    '[+] Registro SRV _sipinternaltls._tcp para puerto 5061 de easydeploy.local registrado.',
    '[+] Registro A "sip.easydeploy.local" -> 192.168.1.10 registrado.',
    '[+] Registro A "lyncdiscoverinternal.easydeploy.local" -> 192.168.1.10 registrado.',
    '[✓] Registros DNS creados de manera correcta. El autodiscover de clientes funcionará sin error.'
  ],

  // System Maintenance
  maint_temp: [
    '⚡ C:\\> powershell.exe -Command "Clear-RecycleBin -Force; Remove-Item $env:TEMP\\* -Recurse -Force -ErrorAction SilentlyContinue"',
    'Iniciando limpieza del almacén de archivos temporales del sistema...',
    '',
    '[i] Liberando archivos en %SystemRoot%\\Temp...',
    '[i] Liberando archivos en %UserProfile%\\AppData\\Local\\Temp...',
    '[i] Vaciando Papelera de Reciclaje...',
    '[+] Archivos de caché de Windows Update eliminados (%SystemRoot%\\SoftwareDistribution\\Download)...',
    '[✓] Limpieza del sistema completada.',
    'Espacio recuperado en disco C: 4.82 GB'
  ],
  maint_registry: [
    '⚡ C:\\> powershell.exe -File .\\Optimize-Registry.ps1',
    'Analizando claves rotas de servicios huérfanos e instaladores antiguos...',
    '',
    '[i] Analizando HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall...',
    '[+] Limpiando 42 punteros de instalación huérfanos.',
    '[i] Optimizando cache de COM+ e interfaces de red obsoletas...',
    '[+] Compactación de base de datos de registro NTUSER.DAT ejecutada.',
    '[✓] Registro de sistema operativo optimizado de manera correcta.'
  ],
  maint_repair: [
    '⚡ C:\\> sfc /scannow',
    'Iniciando análisis del sistema. Este proceso tardará algún tiempo.',
    'Iniciando la fase de comprobación del análisis del sistema.',
    'Comprobación completada al 100%.',
    '',
    '[✓] Protección de recursos de Windows no encontró ninguna infracción de integridad.',
    '',
    '⚡ C:\\> DISM.exe /Online /Cleanup-Image /RestoreHealth',
    '[i] Herramienta Administración y mantenimiento de imágenes de implementación (DISM)...',
    '[i] Comprobando la integridad del almacén de componentes de Windows...',
    '[✓] La operación de restauración se completó correctamente.'
  ]
};
